### ISSUE TITLE
TODO v3

### ISSUE THREAD

**Issue by mjarkk** [mjarkk/wotnlclans#2]
This issue contains feedback from people

- [x] Remove not dutch clans (VABAD)
- [x] Effiency = clanrating
- [x] Global tier 8 to 10
- [x] More tracking script to under the main script

**Comment by mjarkk** [comment]
this is now fixed
